version: '3.7'
services:
    app:
      container_name: react-nginx-app2
      build:
        context: .
        dockerfile: Dockerfile
      image: felipedev21/teste-react:4.0
      ports:
        - '8080:80'
      environment:
        - NODE_ENV=development